# 개요

1. numpy 
2. pandas
3. torch로 vector, matrix 등 만들어보기

## 참고자료
* Official tutorial: https://docs.scipy.org/doc/numpy/reference/
* Stanford Univ. CS231 tutorial: http://cs231n.github.io/python-numpy-tutorial/

## 1. numpy, array, matrix 등

In [2]:
# 버전 차이 warning 무시
import warnings
warnings.filterwarnings("ignore")

In [3]:
import numpy as np

### 리스트, 행렬 선언

In [5]:
# list_name(변수명 설정) = ["item-1", "item-2", ... , "item-n"]

a = [1, 2, 3]
b = ["a", "b", "c"]
c = [["a"], ["a", "b"], ["a", "c"], ["a", "b", "c"]]

print(a)
print(b)
print(c)

[1, 2, 3]
['a', 'b', 'c']
[['a'], ['a', 'b'], ['a', 'c'], ['a', 'b', 'c']]


In [6]:
# append()로 리스트에 item 추가하기
c.append('new_item')
c.append(['new_item_list'])

print(c)

[['a'], ['a', 'b'], ['a', 'c'], ['a', 'b', 'c'], 'new_item', ['new_item_list']]


In [7]:
a = np.array([1, 2, 3])
b = np.array(["a", "b", "c"])
c = np.array([["a"], ["a", "b"], ["a", "c"], ["a", "b", "c"]])

print(a)
print(b)
print(c)

[1 2 3]
['a' 'b' 'c']
[list(['a']) list(['a', 'b']) list(['a', 'c']) list(['a', 'b', 'c'])]


In [11]:
# 배열(또는 행렬)을 1로 채우기
print(np.ones((5, )))
print(np.ones((1, 5)))
print(np.ones((3, 2)))

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
# 배열(또는 행렬)을 0으로 채우기
print(np.zeros((1, 5)))
print(np.zeros((3, 2)))

[[0. 0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [14]:
# 주어진 범위 안에서 순차적으로 증가하는 리스트 만들기
# np.arange([start,] stop, [step, ] dtype=None)

print(np.arange(10))
print(np.arange(3,7, dtype=np.float))
print(np.arange(3,10,2))

[0 1 2 3 4 5 6 7 8 9]
[3. 4. 5. 6.]
[3 5 7 9]


In [15]:
# 행렬 선언하기
mat1 = np.array([[1,2,3],[4,5,6]])

# random으로 matrix 만들기
mat2 = np.random.randint(low=1, high=10, size=(3,2)) # 정수로
mat3 = np.random.rand(3,2) # 정규분포를 따르는 랜덤한 수

print(mat1)
print(mat2)
print(mat3)

[[1 2 3]
 [4 5 6]]
[[1 5]
 [5 8]
 [6 2]]
[[0.07022864 0.22417858]
 [0.44321943 0.78135146]
 [0.99320215 0.54106683]]


### 리스트 인덱싱(Indexing) & 슬라이싱(Slicing)

In [16]:
# Indexing
a = [1,3,5,7,9,11]
print(a[2], a[5], a[-1])

5 11 11


In [17]:
# Slicing
b = [2,4,6,8,10]
print(b[2:])
print(b[:2])
print(b[:]) # 다 갖고 오기

[6, 8, 10]
[2, 4]
[2, 4, 6, 8, 10]


### numpy의 reshape (PyTorch의 view와 비교)

In [18]:
# (row, column)
mat1 = np.random.rand(6,3)
print(mat1)

[[0.46447027 0.43762469 0.05948956]
 [0.99493758 0.60782633 0.60479507]
 [0.36240214 0.76565714 0.67562912]
 [0.42391238 0.07254201 0.44852077]
 [0.03215282 0.3048383  0.15838169]
 [0.79964455 0.2984674  0.36497603]]


In [22]:
# -1: all
print(mat1.reshape(1, -1).shape)
print(mat1.reshape(1, -1))

print("=====")
print(mat1.reshape(-1, 1).shape)
print(mat1.reshape(-1, 1))

print("=====")
print(mat1.reshape(-1).shape)
print(mat1.reshape(-1))

(1, 18)
[[0.46447027 0.43762469 0.05948956 0.99493758 0.60782633 0.60479507
  0.36240214 0.76565714 0.67562912 0.42391238 0.07254201 0.44852077
  0.03215282 0.3048383  0.15838169 0.79964455 0.2984674  0.36497603]]
=====
(18, 1)
[[0.46447027]
 [0.43762469]
 [0.05948956]
 [0.99493758]
 [0.60782633]
 [0.60479507]
 [0.36240214]
 [0.76565714]
 [0.67562912]
 [0.42391238]
 [0.07254201]
 [0.44852077]
 [0.03215282]
 [0.3048383 ]
 [0.15838169]
 [0.79964455]
 [0.2984674 ]
 [0.36497603]]
=====
(18,)
[0.46447027 0.43762469 0.05948956 0.99493758 0.60782633 0.60479507
 0.36240214 0.76565714 0.67562912 0.42391238 0.07254201 0.44852077
 0.03215282 0.3048383  0.15838169 0.79964455 0.2984674  0.36497603]


In [25]:
print(mat1.reshape(2, 9).shape)
print(mat1.reshape(9, 2))

(2, 9)
[[0.46447027 0.43762469]
 [0.05948956 0.99493758]
 [0.60782633 0.60479507]
 [0.36240214 0.76565714]
 [0.67562912 0.42391238]
 [0.07254201 0.44852077]
 [0.03215282 0.3048383 ]
 [0.15838169 0.79964455]
 [0.2984674  0.36497603]]


In [27]:
# mat1.reshape(2,5) => 에러남. 다합쳐서 18 되야함

In [28]:
# tensor 형태로 나타내기
print(mat1.reshape(3,2,3).shape)
print(mat1.reshape(3,2,3))

(3, 2, 3)
[[[0.46447027 0.43762469 0.05948956]
  [0.99493758 0.60782633 0.60479507]]

 [[0.36240214 0.76565714 0.67562912]
  [0.42391238 0.07254201 0.44852077]]

 [[0.03215282 0.3048383  0.15838169]
  [0.79964455 0.2984674  0.36497603]]]


### matrix 또는 tensor 형태에서도 slicing이 가능합니다!

In [30]:
mat2 = np.arange(24).reshape(-1, 4)
print(mat2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [33]:
mat2[:1, :3]

array([[0, 1, 2]])

In [34]:
mat2[3, 0:2]

array([12, 13])

### Math Arithmetic Operations(사칙연산)

In [35]:
x = np.array([[1,3,5],[7,9,11],[13,15,17]])
y = np.array([[2,4,6],[8,10,12],[14,16,18]])

print(x)
print(y)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [36]:
# add
x + y

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

In [37]:
x - y

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [38]:
x * y

array([[  2,  12,  30],
       [ 56,  90, 132],
       [182, 240, 306]])

In [39]:
x / y

array([[0.5       , 0.75      , 0.83333333],
       [0.875     , 0.9       , 0.91666667],
       [0.92857143, 0.9375    , 0.94444444]])

In [40]:
print(x ** 2)
print(np.power(x, 2))

[[  1   9  25]
 [ 49  81 121]
 [169 225 289]]
[[  1   9  25]
 [ 49  81 121]
 [169 225 289]]


In [41]:
np.dot(x, y)

array([[ 96, 114, 132],
       [240, 294, 348],
       [384, 474, 564]])

In [44]:
np.sqrt(x)

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479],
       [3.60555128, 3.87298335, 4.12310563]])

In [53]:
# More on matrix operation
z1 = np.array([[2,2,2]])
z2 = np.array([[2,2]])

print(x.shape, z1.shape, z2.shape)
print(x)
print(z1)
print(z2)

x * z1


(3, 3) (1, 3) (1, 2)
[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[[2 2 2]]
[[2 2]]


array([[ 2,  6, 10],
       [14, 18, 22],
       [26, 30, 34]])

In [56]:
print(z2.shape)
print(x.shape)
# print(x * z2) # shape가 안맞아서 에러

(1, 2)
(3, 3)


In [57]:
# 합
print(x)
print(x.sum(axis = 0)) 
print(x.sum(axis = 1)) 

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[21 27 33]
[ 9 27 45]


In [58]:
# 평균
print(x)
print(x.mean(axis = 0))
print(x.mean(axis = 1))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[ 7.  9. 11.]
[ 3.  9. 15.]


In [59]:
# 표준편차
print(x)
print(x.std(axis = 0))
print(x.std(axis = 1))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[4.89897949 4.89897949 4.89897949]
[1.63299316 1.63299316 1.63299316]


In [64]:
print(x.T) # transpose matrix
print(x.shape, z1.shape, z1.T.shape)
print(z1)
print(np.dot(x, z1.T)) 

[[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]]
(3, 3) (1, 3) (3, 1)
[[2 2 2]]
[[18]
 [54]
 [90]]


### Other operations

In [65]:
xx = np.random.rand(15)
print(xx)

[0.6583995  0.34467334 0.53110319 0.08348093 0.01419435 0.47243495
 0.60507696 0.22888664 0.07830572 0.87975707 0.05972872 0.22918393
 0.72766895 0.74551821 0.02006689]


In [66]:
print(xx)
print(xx.argsort()) # axis를 활용해서 행렬(matrix)에도 적용할 수 있다.
xx.sort()
print(xx)

[0.6583995  0.34467334 0.53110319 0.08348093 0.01419435 0.47243495
 0.60507696 0.22888664 0.07830572 0.87975707 0.05972872 0.22918393
 0.72766895 0.74551821 0.02006689]
[ 4 14 10  8  3  7 11  1  5  2  6  0 12 13  9]
[0.01419435 0.02006689 0.05972872 0.07830572 0.08348093 0.22888664
 0.22918393 0.34467334 0.47243495 0.53110319 0.60507696 0.6583995
 0.72766895 0.74551821 0.87975707]


***

## 2. Pandas

* https://pandas.pydata.org/pandas-docs/stable/

In [67]:
import pandas as pd

### Pandas Series 만들기

* pandas series는 1차원 데이터 집합

In [68]:
pd_series = pd.Series(index = ['a','b','c','d','e'], 
                      data=[1,2,3,4,5])
pd_series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [69]:
# Pandas Series의 기초 정보
print('차원:', pd_series.ndim)
print('형태: ', pd_series.shape)
print('총 원소의 수:', pd_series.size)

print('값:', pd_series.values)
print('인덱스:', pd_series.index)

차원: 1
형태:  (5,)
총 원소의 수: 5
값: [1 2 3 4 5]
인덱스: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


### index를 활용한 데이터 탐색 (중요!)

In [72]:
# loc(index를 활용하여 access), iloc(integer location)

print(pd_series.loc['a']) # 인덱스 값을 알아야함
print(pd_series.iloc[0]) # integer location (인덱스를 몰라도 인덱스 숫자를 입력함)
print()
print(pd_series.loc[['a','c']]) # 인덱스 여러 개를 한번에 주기
print(pd_series.iloc[[0,2]])



1
1

a    1
c    3
dtype: int64
a    1
c    3
dtype: int64


### 데이터 삭제

In [74]:
pd_series.drop('b')

a    1
c    3
d    4
e    5
dtype: int64

In [76]:
print(pd_series)
pd_series.drop('b', inplace=True)
print(pd_series)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
c    3
d    4
e    5
dtype: int64


### Pandas Dataframe 만들기

* 2차원 데이터 집합. 행렬과 비슷하게 row와 column을 갖고 있다

In [77]:
data = {
    'A': np.arange(15),
    'B': np.random.randint(low=0, high=15, size=(15)),
    'C': np.random.rand(15)
}

data_df = pd.DataFrame(data)

In [78]:
data_df

A   B         C
0    0  10  0.289566
1    1  13  0.788697
2    2  10  0.337682
3    3   1  0.153301
4    4   2  0.664554
5    5   6  0.060556
6    6  11  0.518732
7    7   2  0.397660
8    8   2  0.124169
9    9  10  0.282754
10  10  13  0.370221
11  11   5  0.344306
12  12   7  0.351492
13  13  10  0.890958
14  14  14  0.303113

In [79]:
data_df.head()

A   B         C
0  0  10  0.289566
1  1  13  0.788697
2  2  10  0.337682
3  3   1  0.153301
4  4   2  0.664554

In [80]:
data_df.tail()

A   B         C
10  10  13  0.370221
11  11   5  0.344306
12  12   7  0.351492
13  13  10  0.890958
14  14  14  0.303113

In [81]:
data_df.shape

(15, 3)

### Indexing and Slicing

In [82]:
data_df[1:3] # row

A   B         C
1  1  13  0.788697
2  2  10  0.337682

In [83]:
data_df.loc[1] # 인덱스 1번. row

A     1.000000
B    13.000000
C     0.788697
Name: 1, dtype: float64

In [84]:
data_df.loc[1]['C']

0.7886973846873201

In [90]:
data_df.loc[:]['C']

0     0.289566
1     0.788697
2     0.337682
3     0.153301
4     0.664554
5     0.060556
6     0.518732
7     0.397660
8     0.124169
9     0.282754
10    0.370221
11    0.344306
12    0.351492
13    0.890958
14    0.303113
Name: C, dtype: float64

In [89]:
data_df.loc[:][['B', 'C']]

B         C
0   10  0.289566
1   13  0.788697
2   10  0.337682
3    1  0.153301
4    2  0.664554
5    6  0.060556
6   11  0.518732
7    2  0.397660
8    2  0.124169
9   10  0.282754
10  13  0.370221
11   5  0.344306
12   7  0.351492
13  10  0.890958
14  14  0.303113

### Add, Remove and etc

In [91]:
data_df['D'] = data_df['A'] >= 5
data_df

A   B         C      D
0    0  10  0.289566  False
1    1  13  0.788697  False
2    2  10  0.337682  False
3    3   1  0.153301  False
4    4   2  0.664554  False
5    5   6  0.060556   True
6    6  11  0.518732   True
7    7   2  0.397660   True
8    8   2  0.124169   True
9    9  10  0.282754   True
10  10  13  0.370221   True
11  11   5  0.344306   True
12  12   7  0.351492   True
13  13  10  0.890958   True
14  14  14  0.303113   True

In [92]:
data_df.drop('D', axis=1, inplace=True)

In [97]:
data_df.sort_index(axis=0, ascending=False, inplace=True)
data_df

A   B         C
14  14  14  0.303113
13  13  10  0.890958
12  12   7  0.351492
11  11   5  0.344306
10  10  13  0.370221
9    9  10  0.282754
8    8   2  0.124169
7    7   2  0.397660
6    6  11  0.518732
5    5   6  0.060556
4    4   2  0.664554
3    3   1  0.153301
2    2  10  0.337682
1    1  13  0.788697
0    0  10  0.289566